### ISSUE TITLE
Fresh Install not working. python3 issue

### ISSUE THREAD

**Issue by agarbato** [dontobi/MotionEye.rpi#4]
Hi,
Thanks for creating the image.
Not sure how this works for you.
As far as I know motioneye does not work with python3.
Motioneye Installation states you must use python2/pip2  but I can see on the Dockerfile that you install it using pip3.

That's the result.

```motioneye_motioneye_1 is up-to-date
Attaching to motioneye_motioneye_1
motioneye_1  | Traceback (most recent call last):
motioneye_1  |   File "/usr/local/bin/meyectl", line 5, in <module>
motioneye_1  |     from motioneye.meyectl import main
motioneye_1  |   File "/usr/local/lib/python3.9/dist-packages/motioneye/meyectl.py", line 28, in <module>
motioneye_1  |     import settings
motioneye_1  | ModuleNotFoundError: No module named 'settings'```

Ref: https://github.com/ccrisan/motioneye/issues/1048

**Comment by dontobi** [comment]
I will test the current Docker container in the next few days and get to the bottom of the error. If it is Python3, I will provide a Python2 build. I ask for patience.

**Comment by dontobi** [comment]
I have pushed a new version with Python2. Could you test it?

**Comment by dontobi** [comment]
Closed
